# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topics_per_page',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
